# Generated by Django 5.2 on 2025-04-28 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ManualCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_text', models.TextField()),
                ('correction_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.searchquery')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Main title or the product name displayed')),
                ('product_url', models.URLField(blank=True, help_text='url of the product page', max_length=1000, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('is_user_selected', models.BooleanField(default=False, help_text='is the product ticked by the user')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.searchquery')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
            options={
                'ordering': ['search_query', 'website'],
            },
        ),
        migrations.CreateModel(
            name='LearnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('learning_timestamp', models.DateTimeField(auto_now_add=True)),
                ('derived_from_manual_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.manualcorrection')),
                ('search_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.searchquery')),
                ('derived_from_results', models.ManyToManyField(blank=True, to='core.searchresult')),
            ],
        ),
    ]
