# Generated by Django 5.2 on 2025-04-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
