# Generated by Django 5.2 on 2025-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_searchresult_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnedproduct',
            old_name='dosage',
            new_name='dosage_form',
        ),
    ]
